import styles from "../../styles/Home.module.css";
import Head from "/node_modules/next/head";
import Image from "/node_modules/next/image";
import {HiMail} from 'react-icons/hi';

const drVineetDahiya = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SOET KRMU Faculty Dr.Vineet Dahiya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/static/KRMU_LOGO.png" />
      </Head>

      <nav class="flex items-center align-middle bg-ankit-50 md:p-3">
        <img
          class="hidden sm:block md:h-16 md:mr-24 md:ml-5 "
          src="https://www.krmangalam.edu.in/images/KRMULogo_w.svg"
          alt="krmu logo"
        />
        <img
          class="sm:hidden h-20 p-1.5 "
          src="static/KRMU_LOGO.png"
          alt="krmu logo"
        />
        <h1 class="text-2xl md:text-4xl text-white px-1.5 lg:px-auto font-serif">
          School of Engineering & Technology
        </h1>
      </nav>

      <main className={styles.description}>
        <div>
        <div class='flex mt-20'>
        <Image
          src="/dr-vineet-dahiya.jpg"
          height={350}
          width={350}
          className="rounded-full"
        />
        <div class='mx-16'>
        <h1 className="text-2xl lg:text-3xl lg:mt-12 lg:mb-2 italic text-blue-600">
        Dr. Vineet Dahiya
        </h1>
        <h2 class='text-lg'>
        Associate Professor -Engineering & Technology
        </h2>
        <h1 class='flex items-center my-5'>
        <HiMail class='text-xl text-blue-600 mr-2'/>
        <a href="mailto:Vineet.dahiya@krmangalam.edu.in">Vineet.dahiya@krmangalam.edu.in</a>
        </h1>
        
        <div>
          

        </div>
        
        </div>
        
        </div>
        </div>
        
      </main>
    </div>
  );
};

export default drVineetDahiya;
