import Head from "../node_modules/next/head";
import Image from "../node_modules/next/image";
import BgImg from "../public/static/KRMUimg.jpg";

const index = () => {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/static/KRMU_LOGO.png" />
      </Head>
      <div className="h-screen">
        <div className="bg-fixed absolute-z-10">
          <Image src={BgImg} layout="fill" objectFit="cover" quality={100} />
        </div>
        <div>
          <div class="text-black text-3xl text-center ">
            <h1 class="text-black text-5xl animate-pulse drop-shadow-2xl font-serif text-center mt-24">
              This is Home Page !
            </h1>
            <h1 class="drop-shadow-2xl mt-5">
              To see the faculty page please add "/faculty" to your url .
            </h1>
            <h1 class="mt-2 drop-shadow-2xl">or</h1>
            <div class="mt-3">
              <a href="/faculty">
                <button
                  type="button"
                  class="text-white bg-gradient-to-br animate-bounce from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2"
                >
                  Click Here
                </button>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default index;

{
  /* <div class="text-black text-3xl text-center">
        <h1 class="text-black text-5xl animate-pulse drop-shadow-2xl font-serif text-center mt-24">
          This is Home Page !
        </h1>
        <h1 class="mt-5">
          To see the faculty page please add "/faculty" to your url .
        </h1>
        <h1 class="mt-2">or</h1>
        <div class="mt-3">
          <a href="/faculty">
            <button
              type="button"
              class="text-white bg-gradient-to-br animate-bounce from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2"
            >
              Click Here
            </button>
          </a>
        </div>
      </div> */
}
