import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MsAshaSohal from "./ms-asha-sohal";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Faculty Page SOET</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav class="p-3 flex items-center align-middle items-center bg-ankit-50">
        <img
          class="h-20 mr-14 "
          src="https://www.krmangalam.edu.in/images/KRMU%20Logo.svg"
          alt="krmu logo"
        />
        <h1 class="text-5xl text-white px-8 font-serif">
          School of Engineering & Technology
        </h1>
      </nav>

      <main className={styles.description}>
        <h1 className="text-5xl italic text-blue-600">Faculty</h1>

        <p class="my-3">
          Well-experienced and distinguished faculty that works diligently to
          transform students into the most desirable personalities every
          industry demands. These through leaders connect with the students to
          identify their career interests and offer them personalized
          mentorship, enabling them to shine in their respective professions.
        </p>

        <div className="mt-8 flex flex-wrap items-center justify-center text-white gap-y-20 gap-x-11 ">
          
        <div className="backdrop-blur-sm bg-ankit-100 w-[400px] h-[222px] shadow-xl shadow-black rounded-xl flex flex-row hover:scale-105 cursor-pointer ">
            <div className="basis-1/2 text-center font-light mt-4">
              <div className="text-3xl mb-4 italic text-stone-900">Music</div>
              <div class="text-lg text-stone-800">
                Vocal or instrumental sounds (or both) combined in such a way as
                to produce beauty of form, harmony, and expression of emotion.
              </div>
            </div>
            <div className="flex items-center justify-center">
              <Image
                src="/dr-vineet-dahiya.jpg"
                height={250}
                width={250}
                className="rounded-r-xl"
              />
            </div>
          </div>

          <div className="backdrop-blur-sm bg-ankit-100 w-[400px] h-[222px] shadow-xl shadow-black rounded-xl flex flex-row hover:scale-105 cursor-pointer ">
            <div className="basis-1/2 text-center font-light mt-4">
              <div className="text-3xl mb-4 italic text-stone-900">Music</div>
              <div class="text-lg text-stone-800">
                Vocal or instrumental sounds (or both) combined in such a way as
                to produce beauty of form, harmony, and expression of emotion.
              </div>
            </div>
            <div className="flex items-center justify-center">
              <Image
                src="/dr-kaushal-kumar.jpg"
                height={250}
                width={250}
                className="rounded-r-xl"
              />
            </div>
          </div>

          <div className="backdrop-blur-sm bg-ankit-100 w-[400px] h-[222px] shadow-xl shadow-black rounded-xl flex flex-row hover:scale-105 cursor-pointer ">
            <div className="basis-1/2 text-center font-light mt-4">
              <div className="text-3xl mb-4 italic text-stone-900">Music</div>
              <div class="text-lg text-stone-800">
                Vocal or instrumental sounds (or both) combined in such a way as
                to produce beauty of form, harmony, and expression of emotion.
              </div>
            </div>
            <div className="flex items-center justify-center">
              <Image
                src="/dr-shweta-bansal.jpg"
                height={250}
                width={250}
                className="rounded-r-xl"
              />
            </div>
          </div>

          <div className="backdrop-blur-sm bg-ankit-100 w-[400px] h-[222px] shadow-xl shadow-black rounded-xl flex flex-row hover:scale-105 cursor-pointer ">
            <div className="basis-1/2 text-center font-light mt-4">
              <div className="text-3xl mb-4 italic text-stone-900">Music</div>
              <div class="text-lg text-stone-800">
                Vocal or instrumental sounds (or both) combined in such a way as
                to produce beauty of form, harmony, and expression of emotion.
              </div>
            </div>
            <div className="flex items-center justify-center">
              <Image
                src="/ms-asha-sohal.jpg"
                height={250}
                width={250}
                className="rounded-r-xl"
              />
            </div>
          </div>

          <div className="backdrop-blur-sm bg-ankit-100 w-[400px] h-[222px] shadow-xl shadow-black rounded-xl flex flex-row hover:scale-105 cursor-pointer ">
            <div className="basis-1/2 text-center font-light mt-4">
              <div className="text-3xl mb-4 italic text-stone-900">Music</div>
              <div class="text-lg text-stone-800">
                Vocal or instrumental sounds (or both) combined in such a way as
                to produce beauty of form, harmony, and expression of emotion.
              </div>
            </div>
            <div className="flex items-center justify-center">
              <Image
                src="/mr-arvind-kumar.jpg"
                height={250}
                width={250}
                className="rounded-r-xl"
              />
            </div>
          </div>

          <div className="backdrop-blur-sm bg-ankit-100 w-[400px] h-[222px] shadow-xl shadow-black rounded-xl flex flex-row hover:scale-105 cursor-pointer ">
            <div className="basis-1/2 text-center font-light mt-4">
              <div className="text-3xl mb-4 italic text-stone-900">Music</div>
              <div class="text-lg text-stone-800">
                Vocal or instrumental sounds (or both) combined in such a way as
                to produce beauty of form, harmony, and expression of emotion.
              </div>
            </div>
            <div className="flex items-center justify-center">
              <Image
                src="/mr-ashwani-kumar.jpg"
                height={250}
                width={250}
                className="rounded-r-xl"
              />
            </div>
          </div>

          <div className="backdrop-blur-sm bg-ankit-100 w-[400px] h-[222px] shadow-xl shadow-black rounded-xl flex flex-row hover:scale-105 cursor-pointer ">
            <div className="basis-1/2 text-center font-light mt-4">
              <div className="text-3xl mb-4 italic text-stone-900">Music</div>
              <div class="text-lg text-stone-800">
                Vocal or instrumental sounds (or both) combined in such a way as
                to produce beauty of form, harmony, and expression of emotion.
              </div>
            </div>
            <div className="flex items-center justify-center">
              <Image
                src="/mr-surendra-kumar-yadav.jpg"
                height={250}
                width={250}
                className="rounded-r-xl"
              />
            </div>
          </div>

          <div className="backdrop-blur-sm bg-ankit-100 w-[400px] h-[222px] shadow-xl shadow-black rounded-xl flex flex-row hover:scale-105 cursor-pointer ">
            <div className="basis-1/2 text-center font-light mt-4">
              <div className="text-3xl mb-4 italic text-stone-900">Music</div>
              <div class="text-lg text-stone-800">
                Vocal or instrumental sounds (or both) combined in such a way as
                to produce beauty of form, harmony, and expression of emotion.
              </div>
            </div>
            <div className="flex items-center justify-center">
              <Image
                src="/ms-kriti-sharma.jpg"
                height={250}
                width={250}
                className="rounded-r-xl"
              />
            </div>
          </div>

          <div className="backdrop-blur-sm bg-ankit-100 w-[400px] h-[222px] shadow-xl shadow-black rounded-xl flex flex-row hover:scale-105 cursor-pointer ">
            <div className="basis-1/2 text-center font-light mt-4">
              <div className="text-3xl mb-4 italic text-stone-900">Music</div>
              <div class="text-lg text-stone-800">
                Vocal or instrumental sounds (or both) combined in such a way as
                to produce beauty of form, harmony, and expression of emotion.
              </div>
            </div>
            <div className="flex items-center justify-center">
              <Image
                src="/ms-puja-acharya.jpg"
                height={250}
                width={250}
                className="rounded-r-xl"
              />
            </div>
          </div>

        </div>
      </main>


      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
